### ISSUE TITLE
Use case of this vs. `quicli`?

### ISSUE THREAD

**Issue by ErichDonGubler** [killercup/clap-verbosity-flag#1]
I know that you're the author of the `quicli` crate, which seems to have a subset of functionality that conflicts with this (since both crates would set up `env-logger`, right?). Is the use case to have a more minimal set of dependencies and cut out the `main!` macro and its associated `failure` dependency? Perhaps you think that this is more appropriate to use generally now that `?`-in-`main` is available on stable?

**Comment by killercup** [comment]
Good question! :) The next version of quicli will use this crate internally: https://github.com/killercup/quicli/pull/80

I first wrote this as part of quicli, but @yoshuawuyts convinced me that it makes sense to be a crate of its own. This way, people not using quicli can still use this.

(?-in-main still has some unresolved issues, and I'll follow up on that in the next few days.)

I hope that answers your questions!

**Comment by killercup** [comment]
Cool. I'd be glad if you would open a PR to improve the Readme! Right now it also doesn't show how to init the logger using the verbosity type.

> ...do you mean in this issue, or via some other medium? Just want to clarify.

It'll be somewhere else, as it has nothing to do with this crate specifically. :) The current problem is that it's not easy to get rid of quicli's main macro and use ?-in-main instead, as we lose the ability to print out the errors in a _nice_ way. Sadly, right now it seems to depend on some features being added to failure, so I'll have to check with them how to do it once I have a clear idea of what needs to be done.
